language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --dev --no-interaction

script:
  - ./vendor/bin/behat